version: '3.8'

services:
  bot:
    labels:
      - "app=paperbot"

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: ["-config.file=/etc/loki/config.yml"]
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki/config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    depends_on:
      - loki
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./config/promtail/config.yml:/etc/promtail/config.yml:ro

volumes:
  loki-data:
    driver: local

