server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          app: paperbot
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{app="paperbot"}'
          stages:
            - timestamp:
                source: time
                format: RFC3339
      - labeldrop:
          - filename
          - stream

