# paperbot config.yaml

exchange: binance
environment: spot-testnet  # e.g., spot-testnet | spot-live | paper | live
symbols: ["BTC/USDT", "ETH/USDT"]
timeframe: "1m"
fetch:
  rate_limit_ms: 900
  backoff_initial_ms: 500
  backoff_max_ms: 8000

# Feature expansion toggles
features:
  expansion:
    sma_ema: true      # SMA/EMA crossover signals
    macd: false        # MACD indicator
    bollinger: true    # Bollinger Bands
    obv: true          # On-Balance Volume
    keltner: false     # Keltner Channels
    skew_kurtosis: false  # Rolling skewness and kurtosis
    hour_of_day: true  # Hour of day features

# env prefix = f"{exchange.upper()}_{environment.replace('-', '_').upper()}"
# Example: BINANCE_SPOT_TESTNET_API_KEY, BINANCE_SPOT_TESTNET_API_SECRET
