apiVersion: 1
# Provision a default Prometheus data source pointing to the compose service.
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
