apiVersion: 1
groups:
  - orgId: 1
    name: paperbot-patterns
    folder: Alerts
    interval: 1m
    rules:
      - uid: patterns-min-activity
        title: No pattern detections (30m)
        condition: A
        data:
          - refId: A
            queryType: timeSeriesQuery
            datasourceUid: PBFA97CFB590B2093
            relativeTimeRange:
              from: 2700
              to: 0
            model:
              expr: sum(increase(pattern_detected_total[30m])) == 0
              intervalMs: 60000
              maxDataPoints: 43200
              datasource:
                type: prometheus
                uid: PBFA97CFB590B2093
        noDataState: Alerting
        execErrState: Alerting
        for: 45m
        annotations:
            severity: warning
        labels:
            app: paperbot
